# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2fe77a20c2d3238cc4f8df2d900d5e8f29d423345f513217ad4dbbbfb1cec1f5dc4cfaaf18294be39ee0d7db0c4fff4ff94526ccbf04bbf76fd70609468fcf9

test:
  secret_key_base: 6e572cc332c256319df0e6a7a990efaf7a28f8d1b69dfea3c9135ce6ac2945b6387bcb3131f1848ab1b467809e3df87f888f15ef1ca7e8be0de6379bf3ca240e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
